version: '3'
services:

  socks5:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
      - "${PROXY_HEALTHCHECK_PORT}:${PROXY_HEALTHCHECK_PORT}"
